### ISSUE TITLE
Not Found Error

### ISSUE THREAD

**Issue by asad1996172** [edouardfouche/edouardfouche.github.io#1]
Hello,
I have followed every step from here  https://edouardfouche.com/Fun-with-Tensorflow-im2txt/
but i get the following error

NotFoundError (see above for traceback): Tensor name "lstm/basic_lstm_cell/bias" not found in checkpoint files /home/asadmahmood72/Image_to_text/models/im2txt/model.ckpt-3000000
	 [[Node: save/RestoreV2_380 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_380/tensor_names, save/RestoreV2_380/shape_and_slices)]]

My os is UBUNTU 16.04
my tensorflow version is 1.2.0

@edouardfouche  help me!!

**Comment by asad1996172** [comment]
@edouardfouche I have somehow solved the above issue but now i am facing this issue

NotFoundError (see above for traceback): Tensor name "lstm/basic_lstm_cell/kernel" not found in checkpoint files /home/asadmahmood72/Image_to_text/models/im2txt/model.ckpt-3000000
	 [[Node: save/RestoreV2_381 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_381/tensor_names, save/RestoreV2_381/shape_and_slices)]]

**Comment by asad1996172** [comment]
@edouardfouche infact .. the first one still persists..

**Comment by edouardfouche** [comment]
Hi, it looks like the tensorflow API changed again, which makes it incompatible with the checkpoint model. I was using tensorflow 0.12.1 in the article. Can you try with tensorflow 0.12.1 if it works? Otherwise you will have to train the model yourself (expensive) or find a checkpoint file that was generated with a more recent version of tensorflow...

**Comment by asad1996172** [comment]
It worked .. Thanks a ton.!

**Comment by asad1996172** [comment]
is there any way that i could load images from a folder and subfolder in it.?

**Comment by edouardfouche** [comment]
Yes I think if you put the path to all your images separated by a comma in the step
`IMAGE_FILE="${HOME}/im2txt/img.jpg"` you should be able to run the inference on several images. At least that what I can see from the code in `run_inference.py`. You just need to write a small script that returns the absolute path of the images in a folder and subfolders in a string, separated by a comma. Should not be to complicated :) Let me know if it works !

**Comment by asad1996172** [comment]
yup it works. Thanks again

**Comment by asad1996172** [comment]
is there a way to increase the input image size.

Not a JPEG file: starts with 0x89 0x50

InvalidArgumentError (see above for traceback): Invalid JPEG data, size 6535
	 [[Node: decode/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_image_feed_0)]]

**Comment by edouardfouche** [comment]
I am sorry I don't know. If your images are too big I would suggest to downscale them to an acceptable size first.
